# config/packages/security.yaml
security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    your_custom_user_provider:
      id: App\Api\Auth\UserProvider
  firewalls:
    login:
      pattern: ^/api/v1/auth/login
      stateless: true
      json_login:
        check_path: /api/v1/auth/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

  role_hierarchy:
    ROLE_ADMIN: [ ROLE_TEACHER, ROLE_STUDENT ]

  access_control:
    - { path: ^/api/v1/files, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/v1/groups, roles: ROLE_ADMIN }
    - { path: ^/api/v1/labs, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/v1/solutions, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/v1/users, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/v1, roles: PUBLIC_ACCESS }