version: "3.7"

services:
  db:
    image: mysql:8
    container_name: db-labtracker
    volumes:
      - ".db_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - symfony_app
  php:
    build:
      context: ./.docker/php
    container_name: php-labtracker
    volumes:
      - ./:/var/www/symfony:cached
    user: "1000:1000"
    networks:
      - symfony_app
  nginx:
    image: nginx:1.21-alpine
    container_name: nginx-labtracker
    volumes:
      - ./:/var/www/symfony:cached
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - symfony_app

volumes:
  .db_data:

networks:
  symfony_app:
